version: "3.9"

services:

  metadata-api:
    build: 
      context: ./api
      args:
        - GID=51
        - UID=510
        - UNAME=embl
    container_name: metadata_api
    ports:
      - "4000:80"
    restart: unless-stopped
    logging:
      driver: "fluentd"    
    env_file:
      - .env         
  
  metadata_api_v2_publisher:
    build: ./api_v2/rmq_client
    container_name: metadata_api_v2_client
    ports:
      - "4500:80"
      - "4501:5672"
    restart: unless-stopped
    logging:
      driver: "fluentd"    
    env_file:
      - .env  
    depends_on:
      - rabbitmq-server  

  metadata_api_v2_consuner:
    build: ./api_v2/rmq_worker
    container_name: metadata_api_v2_worker
    ports:
      - "4600:80"
      - "4601:5672"
    restart: unless-stopped
    logging:
      driver: "fluentd"    
    env_file:
      - .env      
    depends_on:
      - rabbitmq-server        


  jenkins-server:
    build: ./ci_cd
    container_name: jenkins
    ports: 
      - "4100:8080"
      - "4101:5000"
    volumes:
      - "./ci_cd/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    restart: unless-stopped
    environment:
     - JENKINS_OPTS="--prefix=/jenkins"
    logging:
      driver: "fluentd"     

  nginx-server:
    build: ./reverse_proxy
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped  
    logging:
      driver: "fluentd"     
    env_file:
      - .env    
    depends_on:
      - metadata-api
      - jenkins-server
      - grafana-log-viz
      - rabbitmq-server

  fluentbit-logger:
    build: ./logging/fluentbit
    container_name: fluentbit
    ports:
      - "24225:24225"
    env_file:
      - .env      
    restart: unless-stopped  
    depends_on:
      - postgres-log-db

  fluentd-logger:
    build: ./logging/fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./logging/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - FLUENTD_CONF=fluentd.conf
    restart: unless-stopped

  postgres-log-db:
    build: ./logging/postgresql
    container_name: postgres
    volumes:
      - "./logging/postgresql/pg_data:/var/lib/postgresql/data"
    ports:
      - "4200:5432"
    env_file:
      - .env
    restart: unless-stopped

  grafana-log-viz:
    build: ./logging/grafana
    container_name: grafana
    volumes:
      - "./logging/grafana/gf_data:/var/lib/grafana"    
    ports:
      - "4300:3000"    
    restart: unless-stopped
    depends_on:
      - postgres-log-db    
    logging:
      driver: "fluentd"        
  
  rabbitmq-server:
    build: ./queue
    container_name: rabbitmq
    hostname: embl-queue
    ports:
      - "4400:5672" # AMPQ port
      - "4401:15672" # Management plugin port
    volumes:
      - "./queue/rmq_data:/var/lib/rabbitmq"      
    restart: unless-stopped    
