version: "3.9"

services:

  metadata-api:
    build: ./api
    container_name: metadata_api
    ports:
      - "4000:80"
    restart: unless-stopped
    logging:
      driver: "fluentd"    


  jenkins-server:
    build: ./ci_cd
    container_name: jenkins
    ports: 
      - "4100:8080"
      - "4101:5000"
    volumes:
      - "./ci_cd/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    restart: unless-stopped
    environment:
     - JENKINS_OPTS="--prefix=/jenkins"
    logging:
      driver: "fluentd"     

  nginx-server:
    build: ./reverse_proxy
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped  
    logging:
      driver: "fluentd"     

  # fluentbit-logger:
  #   build: ./logging/fluentbit
  #   container_name: fluentbit

  fluentd-logger:
    build: ./logging/fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./logging/fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      - FLUENTD_CONF=fluentd.conf
    restart: unless-stopped