node {

    checkout scm

    stage 'Build'
    def metadata_api_image = docker.build("metadata_api", "./api")


    stage 'Test'

//     metadata_api_image.inside('-v ${JENKINS_HOME}/results:/api/results -p 5000:80') { c ->

//         sh 'pytest -v --junitxml=results/results.xml'

//     }    
    
//     sh 'docker run metadata_api_image pytest'
    
//     sh 'cat results/results.xml'

    stage 'Deploy'

    

}
