node {

    checkout scm

    stage 'Build'
    def metadata_api_image = docker.build("metadata_api", "./api")


    stage 'Test'

    // mkdir ./results
    // metadata_api_image.run('-v results:results', 'shell pytest -v --junitxml=results/results.xml')

    metadata_api_image.inside {

        sh 'mkdir junit'
        shell 'pytest -v --junitxml=results.xml'
        shell 'cat results.xml'

    }


    stage 'Deploy'

    

}
